name: wecare
version: 1.0.0+5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  #Utilities
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shared_preferences: ^2.0.15
  badges: ^2.0.3
  dropdown_button2: ^1.6.2
  bubble_bottom_bar: ^2.0.0
  url_launcher: ^6.1.6
  flutter_automation: ^2.0.0
  change_app_package_name: ^1.1.0

  #Picker's
  country_picker: ^2.0.15
  image_picker: ^0.8.5+3
  flutter_native_contact_picker: ^0.0.3
  flutter_share: ^2.0.0

  #Authentication
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  pin_code_fields: ^7.4.0
#  geolocator: ^9.0.1
#  geocoding: ^2.0.4

  #Animation
  onboarding_animation: ^0.0.1
  loading_animation_widget: ^1.2.0+2
  delayed_display: ^2.0.0
  lottie: ^1.4.3
  carousel_slider: ^4.1.1
  light_carousel: ^0.0.4
  cached_network_image: ^3.2.2
  flutter_zoom_drawer: ^3.0.3
  floating_action_bubble: ^1.1.4
  simple_speed_dial: ^0.1.7


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "images/hamdam.jpeg"

flutter:
  uses-material-design: true
  assets:
    - images/
    - lottiefiles/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: CrimsonText
      fonts:
        - asset: fonts/CrimsonText-Regular.ttf

